### PR TITLE
Add to-do task input form 

### PR DESCRIPTION
**Pull request by GalKJ**
This feature branch isn't ready to be merged currently.

I'll let you know when Natalia 🙂 

Gal

### CODE REVIEW

**Comment by nataliarusu** [comment]
Hey Gareth, 
what the createTaskHtml() should do? 
1. if you expect it to return only <p> element, I think the better name will be createParagraphEl(), the name of the function should reflect what it does.
2. my suggestion is to name it renderMessage(), this function should take an argument as a message, so it becomes renderMessage(message), then in that function, you create <p> with the message inside it.

**Comment by GalKJ** [comment]
> Hey Gareth, what the createTaskHtml() should do?
> 
>     1. if you expect it to return only  element, I think the better name will be createParagraphEl(), the name of the function should reflect what it does.
> 
>     2. my suggestion is to name it renderMessage(), this function should take an argument as a message, so it becomes renderMessage(message), then in that function, you create  with the message inside it.

Thanks Natalia,

That was just a first test to see if it would return some html. I'm writing various tests and building the function as I fail/pass those tests. I agree with the name of the function but I named it according to what I knew I wanted it to do ultimately.

**Comment by GalKJ** [comment]
Hey N 🙂 

This branch can be reviewed and merged in, there are some conflicts but nothing very complicated. 

Gal

**Comment by nataliarusu** [comment]
feature branch merged to add-header-block

**Pull request closed without merging**
